services: # specifies the "services, apps running"
  app: # name of first service running
    image: swarmpit/swarmpit:latest # image specified, version specified is better than :latest
    environment: # env variables
      - SWARMPIT_DB=http://db:5984 # specifies the needed DB = address
      - SWARMPIT_INFLUXDB=http://influxdb:8086
    volumes: # specifies volumes
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports: # maps HOST : CONTAINER ports
      - 888:8080
    healthcheck:  # Checks health of container
      test: ["CMD", "curl", "-f", "http://localhost:8080"] # cmd run to check for response
      interval: 60s # every min
      timeout: 10s # fails after 10s
      retries: 3 # number of attempts till failure
    networks: # specifies network docker images are able to comm on
      - net # later declared network
    deploy: # gives specifics on how this service should be deployed
      resources: # defines hardware sources
        limits: # limited to (max)
          cpus: '0.50' # % of a CPU usage
          memory: 1024M # total mem used
        reservations: # min resources
          cpus: '0.25'
          memory: 512M
      placement: 
        constraints: # required how/where ran
          - node.role == manager # specifics in swarm, must be run on the manager
